### ISSUE TITLE
Add examples to README

### ISSUE THREAD

**Issue by sananth12** [mani1996/test-case-app#3]
It's slightly unclear what the app's purpose is.
Please add a example or a demo and add a more verbose description of what the app does :)

**Comment by mani1996** [comment]
Sure. I will do it.
For your question, this module can be used as a means to generate and
maintain test cases for competitive programming and the likes of it. I've
written custom methods to invoke system calls and nearly automate the whole
process.

**Comment by mani1996** [comment]
And I'm thinking of creating a simple Django app with this as the base
module  :)

**Comment by sananth12** [comment]
Oh this could be useful! :+1:
